apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 576962245852.dkr.ecr.us-east-1.amazonaws.com/custom-jenkins:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
    name: jenkins-ui
    namespace: default
spec:
    type: NodePort
    selector:
    app: jenkins
    ports:
    - protocol: TCP
        port: 8080
        targetPort: 8080
        name: ui