kind: Service
apiVersion: v1
metadata:
    name: jenkins-ui
    namespace: default
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui
  type: NodePort
